application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^', include('users.urls')),
    url(r'^', include('vacancies.urls')),
    url(r'^', include('specs.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

specs/urls.py
from django.conf.urls import url
from specs import views

app_name = 'specs'

urlpatterns = [
    url(r'^create_spec_type/$',          views.SpecTypeCreateView.as_view(), name='create_spec_type'),
    url(r'^create_spec/$',               views.SpecCreateView.as_view(), name='create_spec'),
    url(r'^lessons/$',                   views.LessonListView.as_view(), name='lessons'),
    url(r'^lessons/create$',             views.LessonCreateView.as_view(), name='create_lesson'),
    url(r'^lessons/(?P<pk>\d+)/detail$', views.LessonDetailView.as_view(), name='lesson_detail'),
    url(r'^lessons/(?P<pk>\d+)/update$', views.LessonUpdateView.as_view(), name='update_lesson'),
    url(r'^lessons/(?P<pk>\d+)/delete$', views.LessonDeleteView.as_view(), name='delete_lesson'),
    url(r'^lessons/(?P<pk>\d+)/pass$',   views.LessonPassView.as_view(), name='pass_lesson'),
    url(r'^lessons/(?P<pk>\d+)/create_test$',                 views.TestCreateView.as_view(), name='create_test'),
    url(r'^tests/create$',                                    views.TestCreateView.as_view(), name='create_test_wo_pk'),
    url(r'^tests/create_ajax$',                               views.test_create, name='create_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/test_detail$',                   views.TestDetailView.as_view(), name='test_detail'),
    url(r'^tests/(?P<pk>\d+)/update$',                        views.TestUpdateView.as_view(), name='update_test'),
    url(r'^tests/(?P<pk>\d+)/update_ajax$',                   views.test_update, name='update_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/delete$',                        views.TestDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<pk>\d+)/delete_ajax$',                   views.test_delete, name='delete_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/start$',                         views.test_start, name='start_test'),
    url(r'^tests/(?P<pk>\d+)/passing$',                       views.test_passing, name='pass_test'),
    url(r'^tests/$',                                          views.TestListView.as_view(), name='tests'),
    url(r'^tests/(?P<pk>\d+)/set$',                           views.TestSetView.as_view(), name='set_test'),
    url(r'^tests/(?P<pk>\d+)/set/create_question$', views.QuestionCreateView.as_view(), name='create_question'),
    url(r'^questions/(?P<pk>\d+)/update$',          views.QuestionUpdateView.as_view(), name='update_question'),
    url(r'^questions/(?P<pk>\d+)/delete$',          views.QuestionDeleteView.as_view(), name='delete_question'),
    url(r'^questions/(?P<pk>\d+)/set$',             views.QuestionSetView.as_view(), name='set_question'),
    url(r'^questions/(?P<pk>\d+)/set/create_answer$', views.AnswerCreateView.as_view(), name='create_answer'),
    url(r'^answers/(?P<pk>\d+)/update$', views.AnswerUpdateView.as_view(), name='update_answer'),
    url(r'^answers/(?P<pk>\d+)/delete$', views.AnswerDeleteView.as_view(), name='delete_answer'),

   ]

trainee/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

specs/models.py
from django.db import models
from django_mysql.models import JSONField
from users.models import User


class SpecType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Spec(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    type = models.ForeignKey(SpecType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Lesson(models.Model):
    trainee = models.ManyToManyField(User, through='TraineeLesson', blank=True)
    name = models.CharField(max_length=50, verbose_name=u'Название')
    spec = models.ForeignKey(Spec, on_delete=models.CASCADE, verbose_name=u'Специальность')
    dsc = models.TextField(max_length=500, verbose_name=u'Описание')
    iframe_link = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'Ссылка на iframe')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TraineeLesson(models.Model):
    NOT_PASSED = 1
    PASSED = 2
    STATUS_CHOICES = ((NOT_PASSED, 'Not passed'),
                      (PASSED, 'Passed'))

    trainee = models.ForeignKey(User, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICES)


class Attachment(models.Model):
    TEXT = 1
    IMAGE = 2
    PRES = 3
    VIDEO = 4
    TYPE_CHOICES = ((TEXT, 'Text'),
                    (IMAGE, 'Image'),
                    (PRES, 'Presentation'),
                    (VIDEO, 'Video'))

    name = models.CharField(max_length=50)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    type = models.SmallIntegerField(choices=TYPE_CHOICES)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Test(models.Model):
    trainee = models.ManyToManyField(User, through='TraineeTest')
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name=u'Урок')
    name = models.CharField(max_length=50, verbose_name=u'Название')
    min_score = models.SmallIntegerField(verbose_name=u'Минимальный проходной балл')
    max_score = models.SmallIntegerField(verbose_name=u'Максимальный балл')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TraineeTest(models.Model):
    NOT_FINISHED = 1
    PASSED = 2
    FAILED = 3
    STATUS_CHOICES = ((NOT_FINISHED, ' Not finished'),
                      (PASSED, 'Passed'),
                      (FAILED, 'Failed'))

    trainee = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    status = models.SmallIntegerField(choices=STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)


class Question(models.Model):
    ONE_ANSWER = 1
    MULTI_ANSWER = 2
    FREE_TEXT = 3
    TYPE_CHOICES = ((ONE_ANSWER, 'One answer'),
                    (MULTI_ANSWER, 'Multiple answers'),
                    (FREE_TEXT, 'Free text answer'))

    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    content = models.TextField(max_length=2000, blank=True, null=True)
    type = models.SmallIntegerField(choices=TYPE_CHOICES)
    additional_params = JSONField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    is_right = models.BooleanField()
    score = models.SmallIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TraineeAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    trainee_test = models.ForeignKey(TraineeTest, on_delete=models.CASCADE)
    additional_params = JSONField(blank=True, null=True)
    is_right = models.BooleanField()

    def __str__(self):
        return 'Answer to: ' + self.question.name

specs/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from specs.models import Lesson, Test, Question, Answer


class LessonCreateForm(forms.ModelForm):
    class Meta:
        model = Lesson
        exclude = ['trainee']


class TestCreateForm(forms.ModelForm):
    class Meta:
        model = Test
        exclude = ['trainee', 'created', 'updated']

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop("request")
    #     super(TestCreateForm, self).__init__(*args, **kwargs)
    #
    # def save(self, commit=True):
    #     test = super(TestCreateForm, self).save(commit=False)
    #     test.user = self.request.user
    #     if commit:
    #         test.save()
    #     return test


class QuestionCreateForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ['created', 'updated']


class AnswerCreateForm(forms.ModelForm):
    class Meta:
        model = Answer
        exclude = ['question', 'created', 'updated']


class SelectOneAnswerForm(forms.Form):
    answers = forms.ModelChoiceField(queryset=Answer.objects.none(), empty_label=None, widget=forms.RadioSelect)

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question', None)
        super(SelectOneAnswerForm, self).__init__(*args, **kwargs)
        self.fields['answers'].queryset = Answer.objects.filter(question=question)

specs/templates/specs/create_answer.html
{% extends "main.html" %} {%block title%}Создание ответа{% endblock %}

{% block javascript %}
    <script>
    $("#id_name").change(function (){
        console.log($(this).val());
    });

    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2>Создание ответа</h2>
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">OK</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/create_lesson.html
{% extends "main.html" %} {%block title%}Создание урока{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2>Создание урока</h2>
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">OK</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/create_question.html
{% extends "main.html" %} {%block title%}Create Question{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2>Create Question</h2>
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">OK</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/create_spec.html
{% extends "main.html" %} {%block title%}Create Spec{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2>Create Spec</h2>
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">OK</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/create_spec_type.html
{% extends "main.html" %} {%block title%}Create Spec Type{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2>Create Spec Type</h2>
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">OK</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/create_test.html
{% extends "main.html" %} {%block title%}Создание теста{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2>Создание теста</h2>
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">OK</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/lesson_detail.html
{% extends "main.html" %} {%block title%}Lesson detail{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h2>{{ object.name }}</h2>
                <p><b>Специальность:</b> {{ object.spec }}</p>
                <p><b>Описание:</b> {{ object.dsc }}</p>

                {% if object.iframe_link %}

                <iframe width="640" height="360" src="{{ object.iframe_link|safe }}" frameborder="0" allowfullscreen></iframe>
                {% endif %}

                {% if is_finished is False %}
                <form method="post" action="{% url 'specs:pass_lesson' pk=object.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success">Завершить</button>
                </form>
                {% else %}
                    <p><button type="button" class="btn btn-success disabled">Завершено</button></p>
                {% endif %}
                {% if user.is_superuser %}
                    <a href="{% url 'specs:create_test' pk=object.pk %}" class="btn btn-primary">Создать тест</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/lessons.html
{% extends "main.html" %} {%block title%}Уроки{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h2>Уроки</h2>
                {% if user.is_authenticated and user.is_admin %}
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{% url 'specs:create_lesson' %}">Добавить новый урок</a></li>
                        <li class="list-group-item"><a href="{% url 'specs:create_spec' %}">Создать новую специальность</a></li>
                        <li class="list-group-item"><a href="{% url 'specs:create_spec_type' %}">Создать новый тип специальности</a></li>
                    </ul>
                {% endif %}

                {% for lesson in object_list %}
                    <ul>
                        <li class="list-group-item">
                            <h3><a href="{% url 'specs:lesson_detail' pk=lesson.pk %}"> {{ lesson.name }}</a></h3>
                            {% if user.is_superuser %}
                                <a href="{% url 'specs:update_lesson' pk=lesson.pk %}" class="btn btn-primary">Изменить </a>
                                <form action="{% url 'specs:delete_lesson' pk=lesson.pk %}" method="post">
                                    {%  csrf_token %}
                                    <input type="hidden" name="pk" value="{{ lesson.pk }}">
                                    <button class="btn btn-danger" type="submit">Удалить</button>
                                </form>
                            {% endif %}
                        </li>


                        <li class="list-group-item">{{ lesson.dsc }}</li>
                        <li class="list-group-item"><b>Дата создания:</b> {{ lesson.created|date:"d.m.Y" }}</li>

                    </ul>
                {% empty %}
                    <ul>
                        <li>Пока еще нет уроков</li>
                    </ul>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/question_set.html
{% extends "main.html" %} {%block title%}Настройка вопроса{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h2>Настройка вопроса</h2>
                <p>Название вопроса: {{ question.name }}</p>
                <p><a href="{% url 'specs:create_answer' pk=question.pk %}">Добавить ответ</a></p>
                <ol>
                {% for answer in answers %}
                    
                    
                        <li><p><h5><b>{{ answer.name }}</b></h5></p>
                        <p>Правильный: {{ answer.is_right|yesno:"Да, Нет" }}</p>
                        <a href="{% url 'specs:update_answer' pk=answer.pk %}" class="btn btn-primary">Изменить </a>
                        <form action="{% url 'specs:delete_answer' pk=answer.pk %}" method="post">
                            {%  csrf_token %}
                            <input type="hidden" name="pk" value="{{ question.pk }}">
                            <button class="btn btn-danger" type="submit">Удалить</button>
                        </form>
                        </li>
                    
                    
                {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/test_detail.html
{% extends "main.html" %} {%block title%}Тест{% endblock %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h2>{{ object.name }}</h2>
                <p>Урок: {{ object.lesson.name }}</p>
                <p>Минимальный проходной балл: {{ object.min_score }}</p>
                <p>Максимальный балл: {{ object.max_score }}</p>

                {% if trainee_test %}
                    <p>Статус выполнения: {{ trainee_test.get_status_display }}</p>
                {% endif %}

                {% if user.is_superuser %}
                    <a href="{% url 'specs:set_test' pk=object.pk %}" class="btn btn-primary">Настроить тест</a>
                {% endif %}

                <button type="button" class="btn btn-primary js-start-test" data-url="{% url 'specs:start_test' pk=object.pk %}">
                    Начать тест
                </button>

                <div class="modal fade" id="modal-test">
                    <div class="modal-dialog">
                        <div class="modal-content">
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/tests.js' %}"></script>
{% endblock %}

specs/templates/specs/test_pass.html
{% extends "main.html" %} {%block title%}Настройка теста{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h2>{{ test.name }}</h2>
                <p>Название теста: {{ test.name }}</p>
                <p><a href="{% url 'specs:tests' %}">Назад к тестам</a></p>
                <p><a href="{% url 'specs:create_question' pk=test.pk %}">Добавить вопрос</a></p>
                <ol>
                {% for question in questions %}


                        <li><p><h5><b>{{ question.name }}</b></h5></p>
                        <p>Тип: {{ question.get_type_display }}</p>
                        <a href="{% url 'specs:update_question' pk=question.pk %}" class="btn btn-primary">Изменить </a>
                        <form action="{% url 'specs:delete_question' pk=question.pk %}" method="post">
                            {%  csrf_token %}
                            <input type="hidden" name="pk" value="{{ question.pk }}">
                            <button class="btn btn-danger" type="submit">Удалить</button>
                        </form>
                        <p><a href="{% url 'specs:set_question' pk=question.pk %}">Настроить ответы</a></p>
                        </li>


                {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/test_passing.html
{% extends "main.html" %} {%block title%}Тесты{% endblock %}
{% load static %}
{% load widget_tweaks %}
{% block javascript %}
    <script src="{% static 'js/tests.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h2 class="page-header">Прохождение теста <strong>{{ question.test.name }}</strong></h2>

                <p><h4><strong>{{ question_number }}. {{ question.name }}</strong></h4></p>


                    
                  <div id="test-form">
                      <form method="post" class="post-form">
                      {% csrf_token %}
{#                          {% for answer in form.answers %}#}
{#                              <div class="radio">{{ answer }}</div>#}
{#                          {% endfor %}#}
                          {{ form.as_p }}
                          <button type="submit" class="btn btn-primary js-next">Далее</button>
                      </form>
                  </div>

            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/test_set.html
{% extends "main.html" %} {%block title%}Настройка теста{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h2>Настройка теста</h2>
                <p>Название теста: {{ test.name }}</p>
                <p><a href="{% url 'specs:tests' %}">Назад к тестам</a></p>
                <p><a href="{% url 'specs:create_question' pk=test.pk %}">Добавить вопрос</a></p>
                <ol>
                {% for question in questions %}
                    
                    
                        <li><p><h5><b>{{ question.name }}</b></h5></p>
                        <p>Тип: {{ question.get_type_display }}</p>
                        <a href="{% url 'specs:update_question' pk=question.pk %}" class="btn btn-primary">Изменить </a>
                        <form action="{% url 'specs:delete_question' pk=question.pk %}" method="post">
                            {%  csrf_token %}
                            <input type="hidden" name="pk" value="{{ question.pk }}">
                            <button class="btn btn-danger" type="submit">Удалить</button>
                        </form>
                        <p><a href="{% url 'specs:set_question' pk=question.pk %}">Настроить ответы</a></p>
                        </li>
                    
                    
                {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock %}

specs/templates/specs/tests.html
{% extends "main.html" %} {%block title%}Тесты{% endblock %}
{% load static %}

{% block javascript %}
    <script src="{% static 'js/tests.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h2 class="page-header">Тесты</h2>

                {% if user.is_authenticated and user.is_admin %}
                    <button type="button"  class="btn btn-primary js-create-test" data-url="{% url 'specs:create_test_ajax' %}">
                        <span class="glyphicon glyphicon-plus"></span>Создать тест
                    </button>
                {% endif %}
                <p></p>
                <div id="tests-list">
                    {% include 'specs/partials/partial_tests_list.html' %}
                </div>
                <div class="modal fade" id="modal-test">
                    <div class="modal-dialog">
                        <div class="modal-content">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}