application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^', include('users.urls')),
    url(r'^', include('vacancies.urls')),
    url(r'^', include('specs.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

specs/urls.py
from django.conf.urls import url
from specs import views

app_name = 'specs'

urlpatterns = [
    url(r'^create_spec_type/$',          views.SpecTypeCreateView.as_view(), name='create_spec_type'),
    url(r'^create_spec/$',               views.SpecCreateView.as_view(), name='create_spec'),
    url(r'^lessons/$',                   views.LessonListView.as_view(), name='lessons'),
    url(r'^lessons/create$',             views.LessonCreateView.as_view(), name='create_lesson'),
    url(r'^lessons/(?P<pk>\d+)/detail$', views.LessonDetailView.as_view(), name='lesson_detail'),
    url(r'^lessons/(?P<pk>\d+)/update$', views.LessonUpdateView.as_view(), name='update_lesson'),
    url(r'^lessons/(?P<pk>\d+)/delete$', views.LessonDeleteView.as_view(), name='delete_lesson'),
    url(r'^lessons/(?P<pk>\d+)/pass$',   views.LessonPassView.as_view(), name='pass_lesson'),
    url(r'^lessons/(?P<pk>\d+)/create_test$',                 views.TestCreateView.as_view(), name='create_test'),
    url(r'^tests/create$',                                    views.TestCreateView.as_view(), name='create_test_wo_pk'),
    url(r'^tests/create_ajax$',                               views.test_create, name='create_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/test_detail$',                   views.TestDetailView.as_view(), name='test_detail'),
    url(r'^tests/(?P<pk>\d+)/update$',                        views.TestUpdateView.as_view(), name='update_test'),
    url(r'^tests/(?P<pk>\d+)/update_ajax$',                   views.test_update, name='update_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/delete$',                        views.TestDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<pk>\d+)/delete_ajax$',                   views.test_delete, name='delete_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/start$',                         views.test_start, name='start_test'),
    url(r'^tests/(?P<pk>\d+)/passing$',                       views.test_passing, name='pass_test'),
    url(r'^tests/$',                                          views.TestListView.as_view(), name='tests'),
    url(r'^tests/(?P<pk>\d+)/set$',                           views.TestSetView.as_view(), name='set_test'),
    url(r'^tests/(?P<pk>\d+)/set/create_question$', views.QuestionCreateView.as_view(), name='create_question'),
    url(r'^questions/(?P<pk>\d+)/update$',          views.QuestionUpdateView.as_view(), name='update_question'),
    url(r'^questions/(?P<pk>\d+)/delete$',          views.QuestionDeleteView.as_view(), name='delete_question'),
    url(r'^questions/(?P<pk>\d+)/set$',             views.QuestionSetView.as_view(), name='set_question'),
    url(r'^questions/(?P<pk>\d+)/set/create_answer$', views.AnswerCreateView.as_view(), name='create_answer'),
    url(r'^answers/(?P<pk>\d+)/update$', views.AnswerUpdateView.as_view(), name='update_answer'),
    url(r'^answers/(?P<pk>\d+)/delete$', views.AnswerDeleteView.as_view(), name='delete_answer'),

   ]

trainee/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

vacancies/urls.py
from django.conf.urls import url
from vacancies import views

app_name = 'vacancies'

urlpatterns = [
    url(r'^vacancies/$', views.VacancyListView.as_view(), name='vacancies'),
    url(r'^vacancies/create$', views.VacancyCreateView.as_view(), name='create'),
    url(r'^vacancies/(?P<pk>\d+)/update$', views.VacancyUpdateView.as_view(), name='update'),
    url(r'^vacancies/(?P<pk>\d+)/delete$', views.VacancyDeleteView.as_view(), name='delete'),
   ]

vacancies/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from specs.models import Spec


class Vacancy(models.Model):
    FULL_TIME = 1
    PART_TIME = 2
    PROJECT = 3
    TYPE_CHOICES = ((FULL_TIME, 'Полная'),
                    (PART_TIME, 'Частичная'),
                    (PROJECT, 'Проектная'))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    trainee = models.ManyToManyField(User, through='TraineeVacancy', related_name='trainees')
    spec = models.ManyToManyField(Spec, verbose_name=u'Специальности')

    name = models.CharField(verbose_name=u'Название', max_length=50)
    dsc = models.TextField(verbose_name=u'Описание', max_length=2000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    address = models.CharField(verbose_name=u'Адрес', max_length=200)
    type = models.SmallIntegerField(verbose_name=u'Тип', choices=TYPE_CHOICES)
    is_remote = models.BooleanField(verbose_name=u'Удаленность', default=False)

    def __str__(self):
        return self.name


class TraineeVacancy(models.Model):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    trainee = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

vacancies/forms.py
from django import forms
from vacancies.models import Vacancy


class VacancyCreateForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        exclude = ['user', 'trainee']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super(VacancyCreateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        vacancy = super(VacancyCreateForm, self).save(commit=False)
        vacancy.user = self.request.user
        if commit:
            vacancy.save()
        return vacancy


class VacancyUpdateForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        exclude = ['user', 'trainee']

vacancies/views.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from vacancies.models import Vacancy
from vacancies.forms import VacancyCreateForm, VacancyUpdateForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404


class VacancyListView(ListView):
    model = Vacancy
    template_name = 'vacancies/vacancies.html'


class VacancyCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('users:login')

    model = Vacancy
    form_class = VacancyCreateForm
    template_name = 'vacancies/create_vacancy.html'
    success_url = reverse_lazy('vacancies:vacancies')

    def get_form_kwargs(self):
        kwargs = super(VacancyCreateView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class VacancyUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('users:login')

    model = Vacancy
    form_class = VacancyUpdateForm
    template_name = 'vacancies/create_vacancy.html'
    success_url = reverse_lazy('vacancies:vacancies')

    def get_object(self, *args, **kwargs):
        vacancy = get_object_or_404(Vacancy, pk=self.kwargs['pk'])
        return vacancy


class VacancyDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('users:login')

    model = Vacancy
    success_url = reverse_lazy('vacancies:vacancies')

    def get(self, request, pk):
        raise NotImplemented

vacancies/templates/vacancies/create_vacancy.html
{% extends "main.html" %} {%block title%}Публикация вакансии{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2>Публикация вакансии</h2>
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">OK</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

vacancies/templates/vacancies/vacancies.html
{% extends "main.html" %} {%block title%}Вакансии{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h2>Вакансии</h2>
                {% if user.is_authenticated and user.is_admin %}
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{% url 'vacancies:create' %}">Добавить вакансию</a></li>
                        <li class="list-group-item"><a href="{% url 'specs:create_spec' %}">Создать специальность</a></li>
                        <li class="list-group-item"><a href="{% url 'specs:create_spec_type' %}">Создать тип специальности</a></li>
                    </ul>
                {% endif %}

                {% for vacancy in object_list %}
                    <ul>
                        <li class="list-group-item">
                            <h3>{{ vacancy.name }}</h3>
                            {% if user.is_superuser %}
                                <a href="{% url 'vacancies:update' pk=vacancy.pk %}" class="btn btn-primary">Изменить </a>
                                <form action="{% url 'vacancies:delete' pk=vacancy.pk %}" method="post">
                                    {%  csrf_token %}
                                    <input type="hidden" name="pk" value="{{ vacancy.pk }}">
                                    <button class="btn btn-danger" type="submit">Удалить</button>
                                </form>
                            {% endif %}
                        </li>

                        <li class="list-group-item"><b>Тип занятости:</b> {{ vacancy.get_type_display }}</li>
                        <li class="list-group-item">{{ vacancy.dsc }}</li>
                        <li class="list-group-item"><b>Дата создания:</b> {{ vacancy.created|date:"d.m.Y" }}</li>
                        <li class="list-group-item"><b>Возможность удаленной работы:</b> {{ vacancy.is_remote|yesno:"Да,Нет" }}</li>
                    </ul>
                {% empty %}
                    <ul>
                        <li>Пока что нет вакансий.</li>
                    </ul>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}