application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^', include('users.urls')),
    url(r'^', include('vacancies.urls')),
    url(r'^', include('specs.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

specs/urls.py
from django.conf.urls import url
from specs import views

app_name = 'specs'

urlpatterns = [
    url(r'^create_spec_type/$',          views.SpecTypeCreateView.as_view(), name='create_spec_type'),
    url(r'^create_spec/$',               views.SpecCreateView.as_view(), name='create_spec'),
    url(r'^lessons/$',                   views.LessonListView.as_view(), name='lessons'),
    url(r'^lessons/create$',             views.LessonCreateView.as_view(), name='create_lesson'),
    url(r'^lessons/(?P<pk>\d+)/detail$', views.LessonDetailView.as_view(), name='lesson_detail'),
    url(r'^lessons/(?P<pk>\d+)/update$', views.LessonUpdateView.as_view(), name='update_lesson'),
    url(r'^lessons/(?P<pk>\d+)/delete$', views.LessonDeleteView.as_view(), name='delete_lesson'),
    url(r'^lessons/(?P<pk>\d+)/pass$',   views.LessonPassView.as_view(), name='pass_lesson'),
    url(r'^lessons/(?P<pk>\d+)/create_test$',                 views.TestCreateView.as_view(), name='create_test'),
    url(r'^tests/create$',                                    views.TestCreateView.as_view(), name='create_test_wo_pk'),
    url(r'^tests/create_ajax$',                               views.test_create, name='create_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/test_detail$',                   views.TestDetailView.as_view(), name='test_detail'),
    url(r'^tests/(?P<pk>\d+)/update$',                        views.TestUpdateView.as_view(), name='update_test'),
    url(r'^tests/(?P<pk>\d+)/update_ajax$',                   views.test_update, name='update_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/delete$',                        views.TestDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<pk>\d+)/delete_ajax$',                   views.test_delete, name='delete_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/start$',                         views.test_start, name='start_test'),
    url(r'^tests/(?P<pk>\d+)/passing$',                       views.test_passing, name='pass_test'),
    url(r'^tests/$',                                          views.TestListView.as_view(), name='tests'),
    url(r'^tests/(?P<pk>\d+)/set$',                           views.TestSetView.as_view(), name='set_test'),
    url(r'^tests/(?P<pk>\d+)/set/create_question$', views.QuestionCreateView.as_view(), name='create_question'),
    url(r'^questions/(?P<pk>\d+)/update$',          views.QuestionUpdateView.as_view(), name='update_question'),
    url(r'^questions/(?P<pk>\d+)/delete$',          views.QuestionDeleteView.as_view(), name='delete_question'),
    url(r'^questions/(?P<pk>\d+)/set$',             views.QuestionSetView.as_view(), name='set_question'),
    url(r'^questions/(?P<pk>\d+)/set/create_answer$', views.AnswerCreateView.as_view(), name='create_answer'),
    url(r'^answers/(?P<pk>\d+)/update$', views.AnswerUpdateView.as_view(), name='update_answer'),
    url(r'^answers/(?P<pk>\d+)/delete$', views.AnswerDeleteView.as_view(), name='delete_answer'),

   ]

trainee/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

specs/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from specs.models import Lesson, Test, Question, Answer


class LessonCreateForm(forms.ModelForm):
    class Meta:
        model = Lesson
        exclude = ['trainee']


class TestCreateForm(forms.ModelForm):
    class Meta:
        model = Test
        exclude = ['trainee', 'created', 'updated']

    # def __init__(self, *args, **kwargs):
    #     self.request = kwargs.pop("request")
    #     super(TestCreateForm, self).__init__(*args, **kwargs)
    #
    # def save(self, commit=True):
    #     test = super(TestCreateForm, self).save(commit=False)
    #     test.user = self.request.user
    #     if commit:
    #         test.save()
    #     return test


class QuestionCreateForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ['created', 'updated']


class AnswerCreateForm(forms.ModelForm):
    class Meta:
        model = Answer
        exclude = ['question', 'created', 'updated']


class SelectOneAnswerForm(forms.Form):
    answers = forms.ModelChoiceField(queryset=Answer.objects.none(), empty_label=None, widget=forms.RadioSelect)

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question', None)
        super(SelectOneAnswerForm, self).__init__(*args, **kwargs)
        self.fields['answers'].queryset = Answer.objects.filter(question=question)

specs/views.py
from specs.models import SpecType, Spec
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, FormView
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.template.loader import render_to_string
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse

from specs.models import Lesson, TraineeLesson, Test, TraineeTest, TraineeAnswer, Question, Answer
from specs.forms import LessonCreateForm, TestCreateForm, QuestionCreateForm, AnswerCreateForm, SelectOneAnswerForm
from specs.mixins.ajax_mixin import AjaxableResponseMixin
from specs import const


class SpecTypeCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('users:login')

    model = SpecType
    fields = ['name']
    template_name = 'specs/create_spec_type.html'
    success_url = reverse_lazy('vacancies:vacancies')


class SpecCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('users:login')

    model = Spec
    fields = ['name', 'type']
    template_name = 'specs/create_spec.html'
    success_url = reverse_lazy('vacancies:vacancies')


class LessonListView(ListView):
    model = Lesson
    template_name = 'specs/lessons.html'


class LessonDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('users:login')

    model = Lesson
    template_name = 'specs/lesson_detail.html'

    def get_object(self, *args, **kwargs):
        lesson = get_object_or_404(Lesson, pk=self.kwargs['pk'])
        return lesson

    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        lesson = context['object']
        try:
            if TraineeLesson.objects.get(trainee=self.request.user, lesson=lesson):
                context['is_finished'] = True
        except ObjectDoesNotExist:
            context['is_finished'] = False
        return context


class LessonCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('users:login')

    model = Lesson
    form_class = LessonCreateForm
    template_name = 'specs/create_lesson.html'
    success_url = reverse_lazy('specs:lessons')


class LessonUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('users:login')

    model = Lesson
    form_class = LessonCreateForm
    template_name = 'specs/create_lesson.html'
    success_url = reverse_lazy('specs:lessons')

    def get_object(self, *args, **kwargs):
        lesson = get_object_or_404(Lesson, pk=self.kwargs['pk'])
        return lesson


class LessonDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('users:login')

    model = Lesson
    success_url = reverse_lazy('specs:lessons')

    def get(self, request, pk):
        raise NotImplemented


class LessonPassView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')

    def get(self, request, pk):
        raise NotImplemented

    def post(self, request, pk):
        lesson = Lesson.objects.get(pk=pk)
        user = request.user
        trainee_lesson = TraineeLesson(trainee=user, lesson=lesson, status=2)
        trainee_lesson.save()

        return redirect(request.META.get('HTTP_REFERER'))


class TestCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('users:login')

    model = Test
    form_class = TestCreateForm
    template_name = 'specs/create_test.html'
    success_url = reverse_lazy('specs:tests')

    # def get_form_kwargs(self):
    #     kwargs = super(TestCreateView, self).get_form_kwargs()
    #     kwargs.update({'request': self.request})
    #     return kwargs

    def get_initial(self):
        if self.kwargs.get('pk'):
            lesson = get_object_or_404(Lesson, pk=self.kwargs.get('pk'))
            name = lesson.name + ' Test'
            return {'lesson': lesson, 'name': name,}
        else:
            super(TestCreateView, self).get_initial()


# class TestCreateAjaxView(LoginRequiredMixin, AjaxableResponseMixin, FormView):
#     login_url = reverse_lazy('users:login')
#     form_class = TestCreateForm
#
#     def get_form_kwargs(self):
#         kwargs = super(TestCreateAjaxView, self).get_form_kwargs()
#         kwargs.update({'request': self.request})
#         return kwargs
#
#     def get(self, request, *args, **kwargs):
#         context = self.get_context_data()
#         html_form = render_to_string('specs/templates/specs/partials/partial_create_test.html',
#                                      context,
#                                      request=self.request,
#                                      )
#         return JsonResponse({'html_form': html_form})
def save_test_form(request, form, template_name):
    data = {}

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            tests = Test.objects.all()

            data['html_tests_list'] = render_to_string('specs/partials/partial_tests_list.html',
                                                       {'object_list': tests},
                                                       request)
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    html_form = render_to_string(template_name,
                                 context,
                                 request=request)
    data['html_form'] = html_form
    return JsonResponse(data)


def test_create(request):
    if request.method == 'POST':
        form = TestCreateForm(request.POST)
    else:
        form = TestCreateForm()
    return save_test_form(request, form, 'specs/partials/partial_create_test.html')


def test_update(request, pk):
    test = get_object_or_404(Test, pk=pk)
    if request.method == 'POST':
        form = TestCreateForm(request.POST, instance=test)
    else:
        form = TestCreateForm(instance=test)
    return save_test_form(request, form, 'specs/partials/partial_update_test.html')


def test_delete(request, pk):
    test = get_object_or_404(Test, pk=pk)
    data = {}
    if request.method == 'POST':
        test.delete()
        data['form_is_valid'] = True
        tests = Test.objects.all()
        data['html_tests_list'] = render_to_string('specs/partials/partial_tests_list.html',
                                                   {'object_list': tests},
                                                   request)
    else:
        context = {'test': test}
        data['html_form'] = render_to_string('specs/partials/partial_delete_test.html',
                                             context,
                                             request)
    return JsonResponse(data)


def test_start(request, pk):
    test = get_object_or_404(Test, pk=pk)
    data = {}
    context = {'test': test}
    if request.method == 'POST':
        TraineeTest.objects.create(test=test, trainee=request.user, status=1)
        questions = Question.objects.filter(test=test)

        context['questions'] = questions
        return redirect('specs:pass_test', pk=pk)
    else:
        data['html_form'] = render_to_string('specs/partials/test_start_confirm.html',
                                             context,
                                             request)
        return JsonResponse(data)


def test_passing(request, pk):
    test = get_object_or_404(Test, pk=pk)
    trainee_test = TraineeTest.objects.get(test=test, trainee=request.user)
    data = {}
    question = Question.objects.filter(test=test)[0]
    context = {'test': test, 'question': question, 'question_number': 1}
    if request.method == 'POST':
        if question.type == const.ONE_ANSWER:
            form = SelectOneAnswerForm(request.POST)
            if form.is_valid():
                answer = form.cleaned_data.get('answers')
                TraineeAnswer.objects.create(question=question,
                                             answer=answer,
                                             is_right=answer.is_right,
                                             trainee_test=trainee_test)
                trainee_test.status = const.PASSED
                return redirect('specs:test_detail', pk=test.pk)
            else:
                return HttpResponse('Not valid')
        else:
            return HttpResponse('Not one answer')
    else:
        form = SelectOneAnswerForm(question=question)
        context['form'] = form
        return render(request, 'specs/test_passing.html', context)


class TestListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('users:login')

    model = Test
    template_name = 'specs/tests.html'


class TestDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('users:login')

    model = Test
    template_name = 'specs/test_detail.html'

    def get_object(self, *args, **kwargs):
        test = get_object_or_404(Test, pk=self.kwargs['pk'])
        return test

    def get_context_data(self, **kwargs):
        context = super(TestDetailView, self).get_context_data(**kwargs)
        test = get_object_or_404(Test, pk=self.kwargs['pk'])
        try:
            tt = TraineeTest.objects.get(trainee=self.request.user, test=test)
            context['trainee_test'] = tt
        except ObjectDoesNotExist:
            pass
        return context


class TestUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('users:login')

    model = Test
    form_class = TestCreateForm
    template_name = 'specs/create_test.html'
    success_url = reverse_lazy('specs:tests')

    def get_object(self, *args, **kwargs):
        test = get_object_or_404(Test, pk=self.kwargs['pk'])
        return test

specs/templates/specs/partials/partial_create_test.html
{% load widget_tweaks %}
<div class="modal-content">
<form method="post" action="{% url 'specs:create_test_ajax' %}" class="js-test-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Создать новый тест</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary">Создать тест</button>
  </div>
</form>
</div>

specs/templates/specs/partials/partial_delete_test.html
{% load widget_tweaks %}
<div class="modal-content">
<form method="post" action="{% url 'specs:delete_test_ajax' pk=test.pk %}" class="js-test-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
      <p class="lead">Вы уверены, что хотите удалить тест <strong>{{ test.name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-danger">Удалить</button>
  </div>
</form>
</div>

specs/templates/specs/partials/partial_tests_list.html
{% for test in object_list %}
    <ul>
        <li class="list-group-item">
            <h3><a href="{% url 'specs:test_detail' pk=test.pk %}"> {{ test.name }}</a></h3>
            {% if user.is_superuser %}
                <button type="button" class="btn btn-primary js-update-test" data-url="{% url 'specs:update_test_ajax' test.pk %}">
                    Изменить
                </button>
                <button type="button" class="btn btn-danger js-delete-test" data-url="{% url 'specs:delete_test_ajax' pk=test.pk %}">
                    Удалить
                </button>
            {% endif %}
        </li>


        <li class="list-group-item"><b>Минимальный проходной балл:</b> {{ test.min_score }}</li>
        <li class="list-group-item"><b>Дата создания:</b> {{ test.created }}</li>

    </ul>
{% empty %}
    <ul>
        <li>Пока еще нет тестов</li>
    </ul>
{% endfor %}

specs/templates/specs/partials/partial_update_test.html
{% load widget_tweaks %}
<div class="modal-content">
<form method="post" action="{% url 'specs:update_test_ajax' form.instance.pk %}" class="js-test-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Изменить тест</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary">Изменить тест</button>
  </div>
</form>
</div>

specs/templates/specs/partials/test_start_confirm.html
{% load widget_tweaks %}
<div class="modal-content">
<form method="post" action="{% url 'specs:start_test' pk=test.pk %}" class="js-test-start-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
      <p class="lead">Вы уверены, что хотите начать тест <strong>{{ test.name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-danger">Приступить</button>
  </div>
</form>
</div>