application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^', include('users.urls')),
    url(r'^', include('vacancies.urls')),
    url(r'^', include('specs.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

specs/urls.py
from django.conf.urls import url
from specs import views

app_name = 'specs'

urlpatterns = [
    url(r'^create_spec_type/$',          views.SpecTypeCreateView.as_view(), name='create_spec_type'),
    url(r'^create_spec/$',               views.SpecCreateView.as_view(), name='create_spec'),
    url(r'^lessons/$',                   views.LessonListView.as_view(), name='lessons'),
    url(r'^lessons/create$',             views.LessonCreateView.as_view(), name='create_lesson'),
    url(r'^lessons/(?P<pk>\d+)/detail$', views.LessonDetailView.as_view(), name='lesson_detail'),
    url(r'^lessons/(?P<pk>\d+)/update$', views.LessonUpdateView.as_view(), name='update_lesson'),
    url(r'^lessons/(?P<pk>\d+)/delete$', views.LessonDeleteView.as_view(), name='delete_lesson'),
    url(r'^lessons/(?P<pk>\d+)/pass$',   views.LessonPassView.as_view(), name='pass_lesson'),
    url(r'^lessons/(?P<pk>\d+)/create_test$',                 views.TestCreateView.as_view(), name='create_test'),
    url(r'^tests/create$',                                    views.TestCreateView.as_view(), name='create_test_wo_pk'),
    url(r'^tests/create_ajax$',                               views.test_create, name='create_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/test_detail$',                   views.TestDetailView.as_view(), name='test_detail'),
    url(r'^tests/(?P<pk>\d+)/update$',                        views.TestUpdateView.as_view(), name='update_test'),
    url(r'^tests/(?P<pk>\d+)/update_ajax$',                   views.test_update, name='update_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/delete$',                        views.TestDeleteView.as_view(), name='delete_test'),
    url(r'^tests/(?P<pk>\d+)/delete_ajax$',                   views.test_delete, name='delete_test_ajax'),
    url(r'^tests/(?P<pk>\d+)/start$',                         views.test_start, name='start_test'),
    url(r'^tests/(?P<pk>\d+)/passing$',                       views.test_passing, name='pass_test'),
    url(r'^tests/$',                                          views.TestListView.as_view(), name='tests'),
    url(r'^tests/(?P<pk>\d+)/set$',                           views.TestSetView.as_view(), name='set_test'),
    url(r'^tests/(?P<pk>\d+)/set/create_question$', views.QuestionCreateView.as_view(), name='create_question'),
    url(r'^questions/(?P<pk>\d+)/update$',          views.QuestionUpdateView.as_view(), name='update_question'),
    url(r'^questions/(?P<pk>\d+)/delete$',          views.QuestionDeleteView.as_view(), name='delete_question'),
    url(r'^questions/(?P<pk>\d+)/set$',             views.QuestionSetView.as_view(), name='set_question'),
    url(r'^questions/(?P<pk>\d+)/set/create_answer$', views.AnswerCreateView.as_view(), name='create_answer'),
    url(r'^answers/(?P<pk>\d+)/update$', views.AnswerUpdateView.as_view(), name='update_answer'),
    url(r'^answers/(?P<pk>\d+)/delete$', views.AnswerDeleteView.as_view(), name='delete_answer'),

   ]

trainee/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^create_profile/$', views.TraineeInfoCreateView.as_view(), name='create_profile'),
    url(r'^edit_profile/$', views.TraineeInfoUpdateView.as_view(), name='edit_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
   ]

vacancies/urls.py
from django.conf.urls import url
from vacancies import views

app_name = 'vacancies'

urlpatterns = [
    url(r'^vacancies/$', views.VacancyListView.as_view(), name='vacancies'),
    url(r'^vacancies/create$', views.VacancyCreateView.as_view(), name='create'),
    url(r'^vacancies/(?P<pk>\d+)/update$', views.VacancyUpdateView.as_view(), name='update'),
    url(r'^vacancies/(?P<pk>\d+)/delete$', views.VacancyDeleteView.as_view(), name='delete'),
   ]

templates/hello.html
{% load static %}

<p> Hello!</p>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Welcome!</title>
</head>
<body>
    <div class="jumbotron text-center">
        <h1>Добро пожаловать на наш портал!</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="text-center">Пожалуйста, <a href="{% url 'users:login' %}">войдите</a>
                    или <a href="{% url 'users:register' %}">зарегистрируйтесь</a></p>
            </div>
        </div>
    </div>

</body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%}{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css"%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" type="text/css">
</head>static/dashboard.css
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'vacancies:vacancies' %}">Learn & Work</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav nav-pills navbar-nav navbar-right">
              {% if user.is_authenticated %}>
                <li><a href="{% url 'users:profile' %}">{{ user.email }}</a></li>
                <li><form id="logout_form" name="logout_form" method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <input type="hidden" name="supporttype" >
                    <input class="btn btn-link" type="submit" value="Выйти">
                </form></li>

              {% else %}
                <li><a href="{% url 'users:login' %}">Войти</a></li>
                <li><a href="{% url 'users:register' %}">Регистрация</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav nav-sidebar">
                <li class="active"><a href="{% url 'vacancies:vacancies' %}">Вакансии </a></li>
                <li><a href="{% url 'specs:lessons' %}">Уроки</a></li>
                <li><a href="{% url 'specs:tests' %}">Тесты</a></li>
              </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
              {% block content %}

              {% endblock %}
            </div>
          </div>
    </div>
    <form id="logout_form" name="logout_form" method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <input type="hidden" name="supporttype" >
    </form>
    <script  src="{% static "jquery/dist/jquery.js"%}"></script>
    <script  src="{% static "bootstrap/dist/js/bootstrap.js"%}" ></script>
    {% block javascript %}{% endblock %}
</body>
</html>